---
- name: Copy web JS config to scripts dir
  template: src=web-config-js.j2
            dest="{{ web_scripts_dir}}/config.js"
  sudo: no

- name: Copy editor JS config to scripts dir
  template: src=editor-config-js.j2
            dest="{{ editor_scripts_dir}}/config.js"
  sudo: no

- { include: development.yml, when: developing }
- { include: staging.yml, when: staging }

