language: python
python:
  - "2.7"

cache:
  directories:
    - schema_editor/node_modules
    - schema_editor/bower_components
    - $HOME/.cache/pip

addons:
    postgresql: "9.4"

env:
  - DJANGO_SETTINGS_MODULE='driver.settings_travis'

before_install:
    # Fun race conditions on npm<2.1.1 when installing packages, so upgrade
    #   https://github.com/npm/npm/issues/6309
  - nvm install 0.12
  - nvm use 0.12

install:
  - gem install -q sass compass
  - pip install "git+https://github.com/azavea/ashlar.git@develop"
  - pip install oauth2_provider
  - pushd schema_editor
  - npm --version
  - npm install -g bower grunt-cli
  - npm install
  - bower install
  - popd

before_script:
  - psql -U postgres -c "create extension postgis"

script:
  - pushd schema_editor
  - grunt test
  - popd
  - pushd app
  - python manage.py test
  - popd
