sudo: required

language: bash

services:
  - docker

install:
  - docker build -f ./app/Dockerfile.base -t "quay.io/azavea/driver-app:${TRAVIS_COMMIT:0:7}" ./app
  - docker build -f ./schema_editor/Dockerfile -t "quay.io/azavea/driver-editor:${TRAVIS_COMMIT:0:7}" ./schema_editor
  - docker build -f ./web/Dockerfile -t "quay.io/azavea/driver-web:${TRAVIS_COMMIT:0:7}" ./web

script: .travis/script.sh

before_deploy:
  - docker login -e . -p "${QUAY_PASSWORD}" -u "${QUAY_USER}" quay.io

deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    repo: WorldBank-Transport/DRIVER
    branch: develop
