---

- name: Install dev packages
  apt: name={{ item }}
  with_items:
    - libgeos-dev
    - binutils
    - libproj-dev
    - gdal-bin

- name: Install Ashlar from source
  command: pip install -e /opt/ashlar
