---

- name: Install python requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'django-oauth-toolkit', version: '0.8.1' }

- name: Install python dev requirements
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - { name: 'ipython', version: '3.0.0' }
    - { name: 'ipdb', version: '0.8' }
  when: developing
  notify: Restart ashlar

- name: Touch log file if it does not exist
  command: touch {{ app_log }}
           creates={{ app_log }}

- name: Set log file permissions
  file: path={{ app_log }} owner={{ app_username }} group={{ app_username }} mode=0664

- name: Create configuration file directory
  file: path={{ root_conf_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0750
        state=directory

- name: Create static files directory
  file: path={{ root_static_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0775
        state=directory

- name: Create media files directory
  file: path={{ root_media_dir }}
        owner={{ app_username }}
        group={{ app_username }}
        mode=0775
        state=directory

- name: Copy app configuration
  template: src=secrets.yaml.j2 dest=/etc/secrets.yaml mode=0660
            owner={{ app_username }} group={{ app_username }}
  notify: Restart ashlar

- name: Copy nginx config
  template: src=nginx-default.j2 dest=/etc/nginx/sites-available/default
  notify: Restart nginx

- name: Run django collectstatic
  django_manage: command=collectstatic app_path={{ root_app_dir }}

- name: Run django migrations
  django_manage: command=migrate app_path={{ root_app_dir }}

- name: Add OAuth2 default application (development only)
  django_manage: command="create_oauth_app admin" app_path={{ root_app_dir }}
  when: developing_or_testing
