---
- name: Create static files directory
  file: path={{ root_static_dir }}
        owner={{ driver_user }}
        group={{ driver_user }}
        mode=0775
        state=directory

- name: Create media files directory
  file: path={{ root_media_dir }}
        owner={{ driver_user }}
        group={{ driver_user }}
        mode=0775
        state=directory

- name: Build application Docker image
  command: >
    docker build
      -f {{ root_app_dir }}/Dockerfile.base
      -t quay.io/azavea/driver-app:latest
      {{ root_app_dir }}
  when: developing

- name: Build application Docker image
  command: >
    docker build
      -f {{ root_app_dir }}/Dockerfile.development
      -t quay.io/azavea/driver-app:latest
      {{ root_app_dir }}
  when: developing

- name: Pull application Docker image
  command: /usr/bin/docker pull quay.io/azavea/driver-app:latest
  when: staging or production
  notify:
    - Restart driver-app

- name: Configure Driver application service definition
  template: src=upstart-app.conf.j2 dest=/etc/init/driver-app.conf
  notify:
    - Restart driver-app

- name: Ensure Driver application is running
  service: name=driver-app state=started

- name: Set up monit monitoring of driver-app container
  template: src=monit-driver-app.cfg.j2 dest=/etc/monit/conf.d/driver-app.cfg
  notify:
    - Restart monit

- name: Run Django collectstatic
  command: >
    /usr/bin/docker exec -i driver-app ./manage.py collectstatic --noinput

- name: Run Django migrations
  command: >
    /usr/bin/docker exec -i driver-app ./manage.py migrate
  when: developing_or_staging
